### PR TITLE
Fixed issue with sending messages

### PR DESCRIPTION
**Pull request by Najsr**
As mentioned in https://github.com/ReSpeak/TS3Hook/pull/18#issuecomment-380630659

### CODE REVIEW

**Comment by Bluscream** [comment]
@splamy can you set up something like travis for compiler checks?

**Comment by Splamy** [comment]
Not unless we find any CI that runs windows.

**Comment by Bluscream** [comment]
Something like https://ci.appveyor.com/project/Luch00/lxbtsc ?

https://ci.appveyor.com/project/ReSpeak/TS3Hook

**Comment by Splamy** [comment]
@Bluscream I added it to appveryor. Didn't knew it worked that well for windows. Last time I checked a few years ago nothing worked correctly and a lot was outdated.

**Comment by Bluscream** [comment]
Can you add the appveor stuff to the readme? ^^

**Comment by Splamy** [comment]
Wait for it :P

**Pull request merged**
